module.exports = {
  products: [
    {
      _id: '1',
      name: 'Viagra 100 mg 4 Tablets',
      active: 'Sildenafil 100mg',
      brand: 'Viagra',
      category: 'Men',
      image: '/images/product-1.jpg',
      reviewsCount: 100,
      price: 77,
      ratings: 4.9,
      stockCount: 100,
    },
    {
      _id: '1',
      name: 'Viagra 100 mg 4 Tablets',
      active: 'Sildenafil 100mg',
      brand: 'Viagra',
      category: 'Men',
      image: '/images/product-1.jpg',
      reviewsCount: 100,
      price: 77,
      ratings: 4.9,
      stockCount: 100,
    },
    {
      _id: '1',
      name: 'Viagra 100 mg 4 Tablets',
      active: 'Sildenafil 100mg',
      brand: 'Viagra',
      category: 'Men',
      image: '/images/product-1.jpg',
      reviewsCount: 100,
      price: 77,
      ratings: 4.9,
      stockCount: 100,
    },
    {
      _id: '1',
      name: 'Viagra 100 mg 4 Tablets',
      active: 'Sildenafil 100mg',
      brand: 'Viagra',
      category: 'Men',
      image: '/images/product-1.jpg',
      reviewsCount: 100,
      price: 77,
      ratings: 4.9,
      stockCount: 100,
    },
    {
      _id: '1',
      name: 'Viagra 100 mg 4 Tablets',
      active: 'Sildenafil 100mg',
      brand: 'Viagra',
      category: 'Men',
      image: '/images/product-1.jpg',
      reviewsCount: 100,
      price: 77,
      ratings: 4.9,
      stockCount: 100,
    },
  ],
};
